server:
  port: 8090

gnss:
  middleware-ip: 193.112.59.171
  public-ip: 192.168.31.102

spring:
  redis:
    host: ${gnss.middleware-ip}
    port: 6379
    password: gps-pro@cn

  rabbitmq:
    host: ${gnss.middleware-ip}
    port: 5672
    username: guest
    password: guest